CREATE DATABASE PRACTICE_DB
CREATE TABLE DEPARTMENT ( DEPT_ID INT, DEPT_NAME VARCHAR(100), LOCATION VARCHAR(100) );

CREATE TABLE EMPLOYEE ( EMP_ID INT, EMP_NAME VARCHAR(100), DEPT_ID INT, SALARY INT, EXPERIENCE INT, MANAGER_ID INT );

CREATE TABLE CUSTOMERS ( CUSTOMER_ID INT, CUSTOMER_NAME VARCHAR(100), CITY VARCHAR(100) );

CREATE TABLE ORDERS ( ORDER_ID INT, CUSTOMER_ID INT, PRODUCT_ID INT, ORDER_AMOUNT INT, ORDER_DATE DATE );

CREATE TABLE PRODUCTS ( PRODUCT_ID INT, PRODUCT_NAME VARCHAR(100), CATEGORY VARCHAR(100), PRICE INT );


INSERT INTO DEPARTMENT VALUES (101,'HR','BANGALORE'), (102,'IT','MUMBAI'), (103,'SALES','DELHI'), (104,'FINANCE','BANGALORE');

INSERT INTO EMPLOYEE VALUES (1,'ANAND',101,50000,3,NULL), (2,'RAHUL',101,70000,5,1), (3,'PRIYA',102,90000,7,1), (4,'NEHA',102,60000,4,3), (5,'VIKAS',103,40000,2,2), (6,'AMIT',103,80000,6,2), (7,'PALLAVI',104,75000,5,3), (8,'KARAN',104,55000,3,7);

INSERT INTO CUSTOMERS VALUES (1,'ROHIT','BANGALORE'), (2,'SIMRAN','MUMBAI'), (3,'ARJUN','DELHI'), (4,'MEGHA','PUNE');

INSERT INTO PRODUCTS VALUES (1001,'LAPTOP','ELECTRONICS',80000), (1002,'MOBILE','ELECTRONICS',30000), (1003,'TABLE','FURNITURE',15000), (1004,'CHAIR','FURNITURE',7000), (1005,'WATCH','ACCESSORIES',10000);

INSERT INTO ORDERS VALUES (1,1,1001,80000,'2025-01-10'), (2,1,1002,30000,'2025-01-12'), (3,2,1003,15000,'2025-02-15'), (4,3,1001,80000,'2025-02-20'), (5,4,1004,7000,'2025-03-01'), (6,2,1005,10000,'2025-03-10'), (7,3,1002,30000,'2025-04-01');


---Find employees earning more than average salary.

SELECT * FROM dbo.EMPLOYEE
SELECT * FROM DEPARTMENT
SELECT * FROM CUSTOMERS
SELECT * FROM ORDERS
SELECT * FROM PRODUCTS


SELECT * FROM dbo.EMPLOYEE WHERE SALARY > (SELECT AVG(SALARY) FROM dbo.EMPLOYEE)

---Find employees earning highest salary.

SELECT * FROM dbo.EMPLOYEE WHERE SALARY =(SELECT MAX(SALARY) FROM dbo.EMPLOYEE)

SELECT TOP(1)* FROM dbo.EMPLOYEE ORDER BY SALARY DESC

---Find second highest salary
SELECT MAX(SALARY) FROM dbo.EMPLOYEE WHERE SALARY < (SELECT MAX(SALARY) FROM dbo.EMPLOYEE)
SELECT * FROM dbo.EMPLOYEE ORDER BY SALARY DESC

SELECT TOP(1) * FROM dbo.EMPLOYEE WHERE SALARY <(SELECT MAX(SALARY) FROM dbo.EMPLOYEE) ORDER BY SALARY DESC

---Find employees working in Bangalore departments.

SELECT * FROM dbo.EMPLOYEE  WHERE DEPT_ID IN (SELECT DEPT_ID FROM DEPARTMENT WHERE LOCATION='BANGALORE')

---Find products costing more than average price.

SELECT * FROM dbo.PRODUCTS WHERE PRICE > (SELECT AVG(PRICE) FROM dbo.PRODUCTS)

---Find customers who placed orders.
select * from customers where customer_id in (select customer_id from orders)

SELECT CUSTOMER_ID, CUSTOMER_NAME, CITY
FROM CUSTOMERS
WHERE CUSTOMER_ID IN (SELECT DISTINCT CUSTOMER_ID FROM ORDERS);

---Find departments having employees with salary greater than 70000.
SELECT * FROM DEPARTMENT WHERE DEPT_ID IN (SELECT DISTINCT DEPT_ID FROM EMPLOYEE WHERE SALARY > 70000)
SELECT * from DEPARTMENT where dept_id in( select dept_id from EMPLOYEE where salary > 70000)

----Find employees earning below average salary.
SELECT * FROM dbo.EMPLOYEE WHERE SALARY < (SELECT AVG(SALARY) FROM dbo.EMPLOYEE)


----Display employee salary along with average salary.

SELECT EMP_NAME, SALARY, (SELECT AVG(SALARY) FROM dbo.EMPLOYEE) AS AVERAGE_SALARY FROM dbo.EMPLOYEE 

-- Derived table: average salary per department, then filter departments 
SELECT 
dept_avg.DepartmentID, 
dept_avg.DeptName, 
dept_avg.AvgSalary 
FROM ( 
SELECT 
d.DepartmentID, 
d.DepartmentName  AS DeptName, 
AVG(e.Salary)     
AS AvgSalary 
    FROM   dbo.Employees   e 
    JOIN   dbo.Departments d ON d.DepartmentID = e.DepartmentID 
    GROUP BY d.DepartmentID, d.DepartmentName 
) AS dept_avg 
WHERE dept_avg.AvgSalary > 70000;

---create cte for employee who are earning more then 60000
select * from dbo.Employee

with high_sal 
AS
(
select * FROM   dbo.Employee where salary>60000
)
select * from high_sal

--- create cte department wise employee count

with dept_count 
AS
(
SELECT DEPT_ID, COUNT(*) AS TOTAL_EMP FROM EMPLOYEE GROUP BY DEPT_ID)
SELECT * FROM dept_count

--- FIND TOP 3 HIGHEST SALARY
SELECT tOP(3) * FROM EMPLOYEE ORDER BY SALARY DESC

SELECT * FROM EMPLOYEE

INSERT INTO EMPLOYEE VALUES (9,'SAKSHI',104,40000,4,1),(10,'PRACHI',103,90000,5,2)
INSERT INTO EMPLOYEE VALUES (11,'SUPRIYA',104,80000,4,1)

WITH RANKED_EMP AS (SELECT *, DENSE_RANK() OVER(ORDER BY SALARY DESC) AS RNK FROM EMPLOYEE)
SELECT EMP_ID,EMP_NAME,SALARY FROM RANKED_EMP WHERE RNK <=3

---FIND DUPLICATE EMPLOYEE USIG CTE
WITH DUPLICATES as(SELECT EMP_NAME,COUNT(*) AS CNT FROM EMPLOYEE GROUP BY EMP_NAME HAVING COUNT(*)>1)
SELECT * FROM DUPLICATES


 SELECT 
        DepT_ID, 
        AVG(Salary) AS AvgSalary, 
        COUNT(*)    AS HeadCount 
    FROM  dbo.Employee 
    GROUP BY DepT_ID
SELECT * FROM EMPLOYEE
    
WITH DeptAvg AS ( 
    SELECT 
        DepT_ID, 
        AVG(Salary) AS AvgSalary, 
        COUNT(*)    AS HeadCount,
        SUM(SALARY)
    FROM  dbo.Employee 
    GROUP BY DepT_ID 
) 
SELECT 
    e.EMP_NAME,  
    e.Salary, 
    da.AvgSalary  AS DeptAvgSalary, 
    e.Salary - da.AvgSalary AS DiffFromAvg 
FROM  dbo.Employee e 
JOIN  DeptAvg da ON da.DepT_ID = e.DepT_ID 
ORDER BY DiffFromAvg DESC; 



