use [ANALYTICS_WITH_ANAND_DB]

create TABLE STUDENTS
(
id INT NOT NULL,
NAME VARCHAR(MAX))

INSERT INTO STUDENTS
VALUES(1,'PRACHI')

SELECT * FROM STUDENTS
INSERT INTO STUDENTS(NAME)
VALUES('SIKHA')

SELECT * FROM STUDENTS
INSERT INTO STUDENTS(ID)
VALUES(3)

DROP TABLE STUDENTS

create TABLE STUDENTS
(
id INT NOT NULL,
NAME VARCHAR(MAX),
CONTACT_NUM VARCHAR(10) UNIQUE)


INSERT INTO STUDENTS
VALUES(1,'PRACHI','8967890856')
INSERT INTO STUDENTS
VALUES(2,'PRACHI','8967890857')

INSERT INTO STUDENTS(NAME)
VALUES('SUPRIYA')

INSERT INTO STUDENTS(ID,)
VALUES(4,)

SELECT*FROM STUDENTS

create TABLE STUDENTS
(
id INT PRIMARY KEY,
NAME VARCHAR(MAX),
CONTACT_NUM VARCHAR(10) UNIQUE)

CREATE TABLE MARKS
(
ID INT,
MARKS FLOAT
FOREIGN KEY(id) REFERENCES STUDENTS(ID)
)

INSERT MARKS VALUES(3,78)

SELECT * FROM MARKS


DROP TABLE STUDENTS

CREATE TABLE VOTER_LIST
(
VOTER_ID INT PRIMARY KEY,
VOTER_NAME VARCHAR(MAX),
VOTER_AGE INT CHECK(VOTER_AGE>=18)
)

INSERT INTO VOTER_LIST VALUES(1,'PRACHI',26)
INSERT INTO VOTER_LIST VALUES(2,'SIKHA',18)

SELECT * FROM VOTER_LIST

CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY,
STATUS VARCHAR(20) DEFAULT 'PENDING')

DROP TABLE ORDERS
INSERT INTO ORDERS(ORDER_ID) VALUES(5)

SELECT * FROM ORDERS

ALTER TABLE ORDERS
DROP CONSTRAINT [DF__ORDERS__STATUS__07C12930]

DROP TABLE PERSONS
CREATE TABLE PERSONS
(
ID INT IDENTITY(2,5),
NAME VARCHAR(30))

INSERT INTO PERSONS
VALUES('PRACHI')

SELECT * FROM PERSONS
