SELECT LEFT('ANALYTICSWITHANAND',10) AS RESULT

SELECT RIGHT('ANALYTICSWITHANAND',9) AS RESULT

SELECT SUBSTRING('ANALYTICSWITHANAND',10,18) AS RESULT

SELECT CHARINDEX('ANAND','ANALYTICSWITHANAND') AS RESULT

SELECT PATINDEX('%WITH%','ANALYTICSWITHANANDWITH') AS RESULT

SELECT STUFF('ANALYTICSWITHANAND',10,5,'FOR') AS RESULT

SELECT REPLICATE('ANALYTICSWITHANAND',2) AS RESULT


CREATE TABLE Employees1
(
EmployeeID INT,
EmployeeName VARCHAR(50),
Department VARCHAR(30)
);

INSERT INTO Employees1
VALUES
(101,'Rahul','IT'),
(102,'Priya','IT'),
(103,'Anand','IT'),
(104,'Neha','HR'),
(105,'Rohit','HR'),
(106,'Amit','Finance');

SELECT Department,
STRING_AGG(EmployeeName, ', ') WITHIN GROUP (ORDER BY EmployeeID DESC) AS EmployeeLIST
FROM Employees1
GROUP BY Department


CREATE TABLE Orders1
(
OrderID INT,
CustomerName VARCHAR(50),
OrderDate DATE,
TotalAmount DECIMAL(10,2)
);

INSERT INTO Orders1
VALUES
(1,'Rahul','2026-06-20',25699.75),
(2,'Priya','2026-07-15',18999.40),
(3,'Anand','2026-08-10',9999.99);

INSERT INTO Orders1 (OrderID, CustomerName, OrderDate)
VALUES
(4,'Rahul','2026-06-20')

SELECT * FROM Orders1


SELECT TotalAmount,
CAST(TotalAmount AS INT) AS ROUND_AMOUNT
FROM Orders1

SELECT CONVERT(INT, TotalAmount) AS ROUND_AMOUNT

FROM Orders1

SELECT CONVERT(VARCHAR,OrderDate,120) AS OrderDateString FROM Orders1

SELECT TRY_CAST('ABC' AS INT) AS Result


SELECT CONVERT(INT,'ABC') AS Result


SELECT FORMAT(TotalAmount,'C','de-DE') AS FormattedAmount FROM Orders1


CREATE TABLE Customers1
(
    CustomerID INT,
    Mobile VARCHAR(15),
    HomePhone VARCHAR(15),
    OfficePhone VARCHAR(15)
);

INSERT INTO Customers1
VALUES
(1,NULL,'08012345678',NULL),
(2,NULL,NULL,'08098765432'),
(3,'9876543210',NULL,NULL);


SELECT *,
       COALESCE(Mobile, HomePhone, OfficePhone) AS ContactNumber FROM Customers1


SELECT NULLIF(100,100) AS Result1, NULLIF(100,200) AS Result2

CREATE TABLE Sales1
(
Product VARCHAR(30),
SalesAmount DECIMAL(10,2),
Quantity INT
);

INSERT INTO Sales1
VALUES
('Laptop',70000,2),
('Mouse',500,0),
('Keyboard',1500,3);


SELECT PRODUCT,SalesAmount/NULLIF(QUANTITY,0) FROM Sales1


--IIF

CASE 
    WHEN 
    THEN 
    ELSE
END


SELECT CHOOSE(1,'Red','Green','Blue') AS Result

SELECT ORDERDATE,CHOOSE(DATEPART(QUARTER,ORDERDATE),'Q1','Q2','Q3','Q4') AS Quarter FROM Orders1

SELECT ORDERDATE,DATEPART(QUARTER,ORDERDATE) AS Quarter FROM Orders1

CREATE TABLE Employees2
(
EmployeeID INT,
EmployeeName VARCHAR(50),
Department VARCHAR(30),
Salary DECIMAL(10,2)
);

INSERT INTO Employees2
VALUES
(1,'Rahul','IT',50000),
(2,'Priya','IT',60000),
(3,'Anand','HR',70000),
(4,'Neha','HR',55000),
(5,'Amit','Finance',65000);

SELECT * FROM EMPLOYEES2 WHERE DEPARTMENT ='IT'

SELECT @@ROWCOUNT AS TOTALROWS

UPDATE Employees2 SET Salary = Salary +5000 WHERE Department = 'HR'

SELECT SCOPE_IDENTITY()

CREATE TABLE Employees4
(
    EmployeeID INT IDENTITY(1,1),
    EmployeeName VARCHAR(50),
    Salary DECIMAL(10,2)
);

INSERT INTO Employees4
VALUES
('HJl',50000);

INSERT INTO Employees4

VALUES

('Neha',55000)

DECLARE @ID INT

SET @ID=SCOPE_IDENTITY()

INSERT INTO AuditLog

VALUES

(@ID,

'Employee Created',

GETDATE());

SELECT @@IDENTITY


BEGIN TRY
  SELECT 10/0;
END TRY
BEGIN CATCH
SELECT ERROR_MESSAGE() AS ErrorMessage,
ERROR_NUMBER() AS ERRORNUMBER;
END CATCH;

BEGIN TRY

SELECT CAST('ABC' AS INT);

END TRY

BEGIN CATCH

SELECT

ERROR_NUMBER(),

ERROR_MESSAGE(),
ERROR_SEVERITY();

END CATCH



CREATE TABLE Employee5
(
    EmployeeID INT,
    Name VARCHAR(50),
    Salary DECIMAL(10,2)
);

INSERT INTO Employee5
VALUES
(1,'Rahul',35000),
(2,'Priya',75000),
(3,'Anand',120000);


CREATE FUNCTION FN_BONUS
(
@SALARY DECIMAL(10,2)
)
RETURNS DECIMAL(10,2)
AS 
BEGIN
DECLARE @BONUS DECIMAL(10,2)
IF @SALARY<50000
SET @BONUS = @SALARY*.20
ELSE IF @SALARY<100000
SET @BONUS = @SALARY * 0.15
ELSE
SET @BONUS = @SALARY * 0.10
RETURN @BONUS
END

SELECT * , DBO.FN_BONUS(Salary) AS BONUS FROM Employee5

CREATE PROCEDURE SP_EMPLOYEE 
AS BEGIN
SELECT * FROM EMPLOYEE5
END
GO

EXEC SP_EMPLOYEE


CREATE PROCEDURE SP_EMP_BY_ID
(
@ID INT
)
AS BEGIN
 SELECT * FROM EMPLOYEE5 WHERE EmployeeID=@ID

END

EXEC SP_EMP_BY_ID 1


CREATE TABLE EMPLOYEE6
(
    EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(30),
    SALARY DECIMAL(10,2),
    BONUS DECIMAL(10,2)
);

INSERT INTO EMPLOYEE6
VALUES
(101,'Rahul','IT',45000,NULL),
(102,'Priya','HR',75000,NULL),
(103,'Amit','Sales',120000,NULL)

SELECT * FROM EMPLOYEE6

-- CALCULATE BONUS ONLY DONT UPDATEW TABLE

CREATE FUNCTION FN_BONUS_EMP6
(
@SALARY DECIMAL(10,2)
)
RETURNS DECIMAL(10,2)
AS BEGIN

DECLARE @BONUS DECIMAL(10,2);

IF @SALARY<50000
SET @BONUS = @SALARY*.20
ELSE IF @SALARY<100000
SET @BONUS = @SALARY * 0.15
ELSE
SET @BONUS = @SALARY * 0.10
RETURN @BONUS
END


SELECT EMP_NAME,SALARY ,DBO.FN_BONUS_EMP6(SALARY) AS BONUS FROM EMPLOYEE6


--- CALCULATE BONUS AND SAVE IT INTO THE BONUS COLUMN

CREATE PROCEDURE SP_UPDATE_BONUS
AS
BEGIN

UPDATE EMPLOYEE6
SET BONUS =
CASE
   WHEN SALARY <50000 THEN SALARY*0.20
   WHEN SALARY <100000 THEN SALARY *.15
   ELSE SALARY * 0.10
END
END

 EXEC SP_UPDATE_BONUS
CREATE PROCEDURE bonus()
BEGIN
    SELECT
        id,
        name,
        salary,
        CASE
            WHEN salary > 10000 THEN salary * 0.15
            WHEN salary > 5000 THEN salary * 0.20
            ELSE 0
        END AS bonus
    FROM Employees;
END;


CREATE TABLE Employee7
(
    EmployeeID INT,
    EmployeeName VARCHAR(50),
    Department VARCHAR(30),
    Salary MONEY,
    City VARCHAR(30)
);

INSERT INTO Employee7
VALUES
(1,'Rahul','IT',50000,'Bangalore'),
(2,'Priya','HR',60000,'Mumbai'),
(3,'Anand','IT',70000,'Delhi'),
(4,'Neha','Finance',65000,'Chennai'),
(5,'Rohit','IT',55000,'Hyderabad')


SELECT * FROM Employee7 WHERE EmployeeID =4
 

CREATE INDEX IX_MPLOYEE_ID
ON EMPLOYEE7(EMPLOYEEID)

SELECT * FROM Employee7 WHERE EmployeeID =4